config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show]
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  root 'posts#index'
  get '/posts/hashtag/:name', to: 'posts#hashtags'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_and_belongs_to_many :tags

  after_create do
    post = Post.find_by(id: self.id)
    hashtags = self.content.scan(/[#][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      post.tags << tag
    end
  end

  before_update do
    post = Post.find_by(id: self.id)
    post.tags.clear
    hashtags = self.content.scan(/[#][\w\p{Han}ぁ-ヶｦ-ﾟー]+/)
    hashtags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      post.tags << tag
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @post = Post.new
    @all_ranks = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    now = Time.current
    @monthly_ranks = Post.find(Like.where(created_at: (now.ago(30.days))..(Time.now)).group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @daily_ranks = Post.find(Like.where(created_at: (now.ago(24.hours))..(Time.now)).group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @minitly_ranks = Post.find(Like.where(created_at: (now.ago(60.seconds))..(Time.now)).group(:post_id).order('count(post_id) desc').limit(3).pluck(:post_id))
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end

  def show
    @post = Post.find(params[:id])
    @like = Like.new
  end

  def hashtags
    @tag = Tag.find_by(name: params[:name])
    @posts = @tag.posts
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to :action => :"index"
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to :action => :"index"
  end

  private
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_with_hashtags(content)
    content.gsub(/[#][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/posts/hashtag/#{word.delete('#')}"}.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LikesApp4</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <p>更新</p>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/posts/hashtags.html.erb
<h2>#<%= @tag.name %></h2>

<% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
  <%= link_to "ユーザー一覧へ", users_path %>

  <hr>

  <div id="tab1" class="tab-pane active">
    <div class="table-container">
      <table class="table table-striped">
        <thead class="bg-danger text-white">
          <tr>
            <th>メールアドレス</th>
            <th>投稿内容</th>
            <th>いいね数</th>
          </tr>
        </thead>
        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><a href="/users/<%= post.user.id %>"><%= post.user.email %></a></td>
              <td><a href="/posts/<%= post.id %>"><%= render_with_hashtags(post.content) %></a></td>
              <td>(<%= post.liked_users.count %>)</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <%= link_to "ユーザー一覧へ", users_path %>
  <%= link_to "ホームへ戻る", posts_path %>

<% else %>
  <%= link_to "ユーザー登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/posts/index.html.erb
<!-- タイトル -->
<h1>いいねサンプル</h1>
<% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, :method => :delete %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
  <%= link_to "ユーザー一覧へ", users_path %>
  <h2>投稿する</h2>
  <%= form_for @post do |f| %>
    <%= f.text_field :content %>
    <%= f.submit %>
  <% end %>
  <hr>

  <h2>検索する</h2>
  <%= search_form_for @q do |f| %>
    <%= f.label :content, "キーワード" %>
    <%= f.search_field :content_cont %>

    <%= f.submit "検索"  %>
  <% end %>

  <h2>投稿一覧</h2>
    <div id="tab1" class="tab-pane active">
      <div class="table-container">
        <table class="table table-striped">
          <thead class="bg-danger text-white">
            <tr>
              <th>メールアドレス</th>
              <th>投稿内容</th>
              <th>いいね数</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><a href="/users/<%= post.user.id %>"><%= post.user.email %></a></td>
                <td><a href="/posts/<%= post.id %>"><%= render_with_hashtags(post.content) %></a></td>
                <td>(<%= post.liked_users.count %>)</td>
                <% if post.user_id == current_user.id %>
                  <td><%= link_to "削除", post_path(post), method: :delete, data: { confirm: "削除しますか？" } %></td>
                  <td><%= link_to "編集", edit_post_path(post), method: :get %></td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <hr>

  <h2>いいねランキング</h2>

<!-- タブボタンの設定 -->
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a href="#tab1" class="nav-link" data-toggle="tab">総合いいね数ランキング表</a>
    </li>
    <li class="nav-item">
      <a href="#tab2" class="nav-link" data-toggle="tab">月間いいね数ランキング表</a>
    </li>
    <li class="nav-item">
      <a href="#tab3" class="nav-link" data-toggle="tab">日間いいね数ランキング表</a>
    </li>
    <li class="nav-item">
      <a href="#tab4" class="nav-link" data-toggle="tab"> 1分間いいね数ランキング表</a>
    </li>
  </ul>


<!-- コンテンツの設定 -->
  <div class="tab-content">
    <div id="tab1" class="tab-pane active">
      <div class="table-container">
        <table class="table table-striped">
          <thead class="bg-danger text-white">
            <tr>
              <th>順位</th>
              <th>メールアドレス</th>
              <th>投稿内容</th>
              <th>いいね数</th>
            </tr>
          </thead>
          <tbody>
            <% @all_ranks.each.with_index(1) do |post, i| %>
              <tr>
                <td>第<%= i %>位</td>
                <td><a href="/users/<%= post.user.id %>"><%= post.user.email %></a></td>
                <td><a href="/posts/<%= post.id %>"><%= render_with_hashtags(post.content) %></a></td>
                <td>(<%= post.liked_users.count %>)</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div id="tab2" class="tab-pane">
      <div class="table-container">
        <table class="table table-striped">
          <thead class="bg-danger text-white">
            <tr>
              <th>順位</th>
              <th>メールアドレス</th>
              <th>投稿内容</th>
              <th>いいね数</th>
            </tr>
          </thead>
          <tbody>
            <% @monthly_ranks.each.with_index(1) do |post, i| %>
              <tr>
                <td>第<%= i %>位</td>
                <td><a href="/users/<%= post.user.id %>"><%= post.user.email %></a></td>
                <td><a href="/posts/<%= post.id %>"><%= render_with_hashtags(post.content) %></a></td>
                <td>(<%= post.liked_users.count %>)</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div id="tab3" class="tab-pane">
      <div class="table-container">
        <table class="table table-striped">
          <thead class="bg-danger text-white">
            <tr>
              <th>順位</th>
              <th>メールアドレス</th>
              <th>投稿内容</th>
              <th>いいね数</th>
            </tr>
          </thead>
          <tbody>
            <% @daily_ranks.each.with_index(1) do |post, i| %>
              <tr>
                <td>第<%= i %>位</td>
                <td><a href="/users/<%= post.user.id %>"><%= post.user.email %></a></td>
                <td><a href="/posts/<%= post.id %>"><%= render_with_hashtags(post.content) %></a></td>
                <td>(<%= post.liked_users.count %>)</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div id="tab4" class="tab-pane">
      <div class="table-container">
        <table class="table table-striped">
          <thead class="bg-danger text-white">
            <tr>
              <th>順位</th>
              <th>メールアドレス</th>
              <th>投稿内容</th>
              <th>いいね数</th>
            </tr>
          </thead>
          <tbody>
            <% @minitly_ranks.each.with_index(1) do |post, i| %>
              <tr>
                <td>第<%= i %>位</td>
                <td><a href="/users/<%= post.user.id %>"><%= post.user.email %></a></td>
                <td><a href="/posts/<%= post.id %>"><%= render_with_hashtags(post.content) %></a></td>
                <td>(<%= post.liked_users.count %>)</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

<% else %>
  <%= link_to "ユーザー登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>

app/views/posts/show.html.erb
<h1>投稿詳細ページ</h1>
<h3><a href="/users/<%= @post.user.id %>"><%= @post.user.email %></a></h3>
<h3><a href="/posts/<%= @post.id %>"><%= render_with_hashtags(@post.content) %></a></h3>
<h3>いいね件数: <%= @post.likes.count %></h3>
<% if @post.user_id == current_user.id %>
  <h3><%= link_to "削除", post_path(@post), method: :delete, data: { confirm: "削除しますか？" } %></h3>
  <h3><%= link_to "編集", edit_post_path(@post), method: :get %></h3>
<% end %>

<% if current_user.already_liked?(@post) %>
  <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
<% else %>
  <%= button_to 'いいね', post_likes_path(@post) %>
<% end %>
<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><a href="/users/<%= user.id %>"><%= user.email %></a></li>
<% end %>

<%= link_to "ホームへ戻る", posts_path %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
  <a href="/users/<%= user.id %>"><%= user.email %></a>
  <hr>
<% end %>
<%= link_to "ホームへ戻る", posts_path %>

app/views/users/show.html.erb
<h1>ユーザー詳細ページ</h1>
<h3><%= @user.email %></h3>
<h2>投稿内容</h2>
<% @user.posts.each do |post| %>
  <a href="/posts/<%= post.id %>"><%= render_with_hashtags(post.content) %></a>
  <hr>
<% end %>
<h3>いいねしている投稿</h3>
  <% @user.liked_posts.each do |post| %>
    <tr>
      <td><a href="/users/<%= post.user.id %>"><%= post.user.email %></a></td>
      <td><a href="/posts/<%= post.id %>"><%= render_with_hashtags(post.content) %></a></td>
    </tr>
    <hr>
  <% end %>


<%= link_to "ユーザー一覧へ", users_path %>
<%= link_to "ホームへ戻る", posts_path %>